version: '2'
services:
  datos:
    image: busybox
    volumes:
      - ../:/app
      # /etc/localtime:/etc/localtime:ro 
      # - ~/etc/timezone:/etc/localtime:ro
      # - /etc/timezone:/etc/localtime:ro
    networks:
      - devinexoos
  demo:
    build:
      context: ./docker
    volumes_from:
      - datos
    ports:
        - "9090:9090"
    expose:
      - "9090"
    networks:
      - devinexoos
    external_links:
      - redis:redis
    depends_on:
      - datos
      # - smtp
networks:
  devinexoos:
    external: true
